services:
  db:
    image: "postgres:14.21-alpine3.23"
    restart: always
    environment: 
      POSTGRES_DB: db_lab1
      POSTGRES_USER: user_lab1
      POSTGRES_PASSWORD: password_lab1
    volumes:
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql

  app: 
    build: .
    depends_on:
      - db
    volumes:
      - ./data:/code/data
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: db_lab1
      DB_USER: user_lab1
      DB_PASSWORD: password_lab1
      DATA_PATH: /code/data/
    stdin_open: true
    tty: true
    